using System;
using UnityEngine;

namespace Apex.Renegade
{
    internal static class ApexPortMaterialFactory
    {
        private const string RuntimeLitResource = "Apex/RuntimeLit";

        public static Material Create(string name, Color color, float metallic, Color emission = default)
        {
            Material material;
            var template = Resources.Load<Material>(RuntimeLitResource);
            if (template != null)
            {
                material = new Material(template);
            }
            else
            {
                // Editor/dev fallback only. The standalone build is expected to carry
                // Assets/ApexPort/Resources/Apex/RuntimeLit.mat, generated by ApexBatch.
                var shader = Shader.Find("Standard") ?? Shader.Find("Unlit/Color");
                if (shader == null)
                    throw new InvalidOperationException(
                        "Apex runtime material shader is unavailable. Expected Resources/Apex/RuntimeLit or a built-in fallback shader.");
                material = new Material(shader);
            }

            material.name = name;
            material.color = color;
            if (material.HasProperty("_Metallic")) material.SetFloat("_Metallic", Mathf.Clamp01(metallic));
            if (material.HasProperty("_Glossiness")) material.SetFloat("_Glossiness", 0.40f);

            if (material.HasProperty("_EmissionColor"))
            {
                // The generated template has the emission variant enabled so the player
                // build retains this variant even when individual clones emit black.
                material.EnableKeyword("_EMISSION");
                material.SetColor("_EmissionColor", emission);
            }

            return material;
        }
    }
}
